name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  FOUNDRY_PROFILE: default

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install --no-commit

      - name: Install FHE dependencies
        run: |
          forge install fhenixprotocol/cofhe-contracts --no-commit
          forge install fhenixprotocol/cofhe-mock-contracts --no-commit

      - name: Check formatting
        run: forge fmt --check

      - name: Run forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run deployment scripts
        run: |
          forge script deploy/EncryptedStorage.s.sol
        id: deploy